noprefetch = false
no_background_fetch = true
disable_verification = true
prefetch_async_size = 1
# metrics_address = "127.0.0.1:8234"

[[resolver.host."localhost:5000".mirrors]]
host = "localhost:5000"
insecure = true
