global:
  scrape_interval: 0s500ms

scrape_configs:
  - job_name: "stargz-snapshotter"
    static_configs:
      - targets: ["benchmark:9333"]

  - job_name: "containerd"
    static_configs:
      - targets: ["benchmark:9334"]
    metrics_path: /v1/metrics
